export const STORE_USER_INPUT = 'STORE_USER_INPUT';
export const UPDATE_WORD_ON_FOCUS = 'UPDATE_WORD_ON_FOCUS';
export const TOGGLE_TEXT_EDITABLE = 'TOGGLE_TEXT_EDITABLE';
export const UPDATE_DIALOG_INFO = 'UPDATE_DIALOG_INFO';
export const UPDATE_SETTING = 'UPDATE_SETTING';
export const UPDATE_INDEX_TO_EXPAND = 'UPDATE_INDEX_TO_EXPAND';

export const UPDATE_SYNONYM_LIST = 'UPDATE_SYNONYM_LIST';